---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: dominiquefuchs.grafana_compose
      vars:
        gc_service_manage: true
        gc_alertmanager_default_receiver: test-receiver
        gc_alertmanager_receivers:
          - name: test-receiver
            telegram_configs:
              - bot_token: '123456'
                send_resolved: true
                api_url: 'https://api.telegram.example'
                chat_id: -123456
                parse_mode: ''
