---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ansible-lint .
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-dfuchs/alma-9-ansible}:latest
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge_default.yml}
scenario:
  test_sequence:
#    - dependency
#    - cleanup
    - destroy
    - syntax
    - create
#    - prepare
    - converge
    - idempotence
#    - side_effect
    - verify
#    - cleanup
    - destroy
verifier:
  name: ansible
