---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: dominiquefuchs.grafana_compose
      vars:
        gc_service_manage: true
        gc_node_exporters: ['127.0.0.1:9100', '127.0.0.1:9100']
